version: '3.8'

services:
    db:
        container_name: postgres-assembly-shop
        # build: ./postgres
        image: 'postgres:alpine'
        env_file:
            - ./.env
        ports:
            - '5432:5432'

    app:
        container_name: assembly-shop-api
        build: ./
        env_file:
            - ./.env
        ports:
            - '3000:3000'
        volumes:
            - ./:/usr/assembly-shop-api
