version: '3.8'

services:
    # PostgresSQL
    postgres:
        container_name: postgres-assembly-shop
        build: ./postgres
        env_file:
            - ./.env
        ports:
            - '5432:5432'

    # Redis
    redis:
        container_name: redis-assembly-shop
        image: redis:latest
        ports:
            - '6379:6379'

    # Backend
    manual-mode-api:
        container_name: assembly-shop-api
        build: ./
        env_file:
            - ./.env
        command: npm run dev
        ports:
            - '3000:3000'
        volumes:
            - ./:/usr/assembly-shop-api
